### ISSUE TITLE
Sublime text 3 throwing error

### ISSUE THREAD

**Issue by saas786** [cedaro/esformatter-wordpress#4]
Hi,

I am trying to use it with Sublime, when I run ESFormatter command initialy it has thrown the error regarding "esformatter-wordpress" not found, then I installed it with -g and it works.

But I received new error now, it says "stdin quotes.tokenBefore" not found

Can you please help me understand why its throwing this error?

**Comment by ghost** [comment]
Using this from the command line myself, but also receiving this error.

**Comment by bradyvercher** [comment]
Thanks for the report, @saas786. Like @corvannoorloos, I was able to reproduce this on the command line and [traced it down to a change](https://github.com/millermedeiros/esformatter-quotes/commit/93f1adc297cc74cb6dff5b7db0cecc322413afd6) in the `esformatter-quotes` plugin.

I'll spend a little more time testing when I get a chance, but the fix should just require updating the call from `quotes.tokenBefore()` to `quotes.tokenAfter()` and moving it into an `exports.tokenAfter()` method in `index.js`.

**Comment by bradyvercher** [comment]
@saas786 @corvannoorloos I believe 353bf2e should take care of this. If y'all an confirm it works, I'll go ahead and tag a new release.

**Comment by ghost** [comment]
@bradyvercher https://github.com/cedaro/esformatter-wordpress/commit/353bf2e7cf97462abd2d64b64ac932483171cada fixes the issue for me on the command line. Thanks for having taken a look at this during the holidays!

**Comment by saas786** [comment]
@bradyvercher It doesn't work for me in sublime text 3,

I have installed it again (with -g) and it still throws error for me

**Comment by ghost** [comment]
@saas786 These are just my first attempts using esformatter-wordpress + Sublime Text, but after https://github.com/cedaro/esformatter-wordpress/commit/353bf2e7cf97462abd2d64b64ac932483171cada I'm running this without any issues.

I have installed:
- https://github.com/piuccio/sublime-esformatter as a Sublime Text package
- `npm install -g esformatter`
- `npm install -g github:cedaro/esformatter-wordpress#develop` (https://github.com/cedaro/esformatter-wordpress/commit/353bf2e7cf97462abd2d64b64ac932483171cada isn't published to the npm repo yet)
- and have a [default](https://github.com/cedaro/esformatter-wordpress#esformatter) `.esformatter` configuration file in my plugin/theme root folder

Which Sublime Text package are you using and have you installed `npm install -g github:cedaro/esformatter-wordpress#develop`?

**Comment by saas786** [comment]
@corvannoorloos Thanks for the info, by installing develop branch, it works now.

**Comment by bradyvercher** [comment]
Thanks for testing and confirming it works. I've gone ahead pushed out version 0.2.1 to wrap this up.

@corvannoorloos Thanks for lending a hand and taking the time to post your steps for testing. It's much appreciated!
